version: "3.7"
services:
  mongo:
    image: "mongo:4.2.1"
    ports: 
      - "27017:27017"
    network_mode: host

  app:
    build: .
    ports:
      - "8080:8080"
    network_mode: host
    depends_on:
      - mongo