---
micronaut:
    application:
        name: graphql-sample
    server:
        port: 8082

---
graphql:
    enabled: true
    path: /graphql
    graphiql:
        enabled: true
        path: /graphiql
        template-path: classpath:graphiql/index.html
        page-title: GraphiQL

